/**
 * 389. Find the Difference
 * easy
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * Finds the extra character in string `t` compared to string `s`.
 * Assumes `t` is generated by shuffling `s` and adding one additional character.
 *
 * @param {string} s - The original string.
 * @param {string} t - The modified string containing all characters of `s` plus one extra.
 * @returns {string} The extra character present in `t` but not in `s`.
 *
 * @example
 * findTheDifference('abcd', 'abcde');
 * // returns 'e'
 *
 * @example
 * findTheDifference('', 'y');
 * // returns 'y'
 */

function findTheDifference(s, t) {
  const mapS = {};
  const mapT = {};
  for (const each of s) {
    mapS[each] = (mapS[each] || 0) + 1;
  }
  for (const each of t) {
    mapT[each] = (mapT[each] || 0) + 1;
  }
  for (const each in mapT) {
    if (!mapS[each]) return each;
    if (mapS[each] !== mapT[each]) return each;
  }
}
